// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveMigrationDatabaseConnectionString } from "./src/lib/postgres-connection";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations usam conexão direta; o runtime serverless continua pooled.
    url: resolveMigrationDatabaseConnectionString(process.env),
  },
});
