'use client'

import { ChevronLeft, ChevronRight, Home, Info, Package } from 'lucide-react'
import { brl } from '@/lib/client-api'
import type { DashboardDto } from '@/lib/client-types'
import { MetricCard, PageHeader } from './ui'

export function FlowScreen({ data, changeMonth, selectCategory, loading }: {
  data: DashboardDto
  changeMonth: (delta: number) => void
  selectCategory: (id: string | null) => void
  loading: boolean
}) {
  const max = Math.max(1, ...data.history.map((item) => item.totalSpent))
  const selected = data.classification.selected
  const color = selected?.color ?? '#635BFF'
  const title = selected?.name ?? 'Tudo'
  const composition = data.classification.children
  const products = data.classification.products

  return <div className="relative px-4 pb-8 md:px-6">
    <PageHeader title="Análise de fluxo" subtitle="Navegue pelo seu plano de contas" action={<div className="flex items-center rounded-lg bg-slate-100 p-1"><button aria-label="Mês anterior" onClick={() => changeMonth(-1)} className="p-1 text-slate-400"><ChevronLeft size={14} /></button><span className="min-w-20 text-center text-[9px] font-bold">{data.monthLabel} {data.year}</span><button aria-label="Próximo mês" onClick={() => changeMonth(1)} className="p-1 text-slate-400"><ChevronRight size={14} /></button></div>} />

    <nav aria-label="Classificação do relatório" className="-mx-4 mb-4 flex gap-2 overflow-x-auto border-b border-slate-100 px-4 py-3 scrollbar-none md:-mx-6 md:px-6">
      <button onClick={() => selectCategory(null)} className={'inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1.5 text-[8px] font-semibold ' + (!selected ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-500')}><Home size={10} /> Tudo</button>
      {data.classification.breadcrumbs.map((item, index) => <button key={item.id} onClick={() => selectCategory(item.id)} className={'inline-flex shrink-0 items-center gap-1 rounded-full px-2.5 py-1.5 text-[8px] font-semibold ' + (index === data.classification.breadcrumbs.length - 1 ? 'text-white' : 'bg-slate-100 text-slate-500')} style={index === data.classification.breadcrumbs.length - 1 ? { background: item.color } : undefined}><span>{item.icon}</span>{item.name}</button>)}
    </nav>

    <div className="grid grid-cols-2 gap-3 min-[420px]:grid-cols-3 [&>*:last-child]:col-span-2 min-[420px]:[&>*:last-child]:col-span-1"><MetricCard label="Desembolso total" value={brl(data.totalSpent, 0)} detail={String(data.purchaseCount) + (data.purchaseCount === 1 ? ' compra' : ' compras')} /><MetricCard label="Média / mês" value={brl(data.history.reduce((sum, item) => sum + item.totalSpent, 0) / 6, 0)} detail="últimos 6 meses" tone="violet" /><MetricCard label="Parcela mensal estimada" value={brl(data.estimatedConsumption, 0)} detail="pela classificação cadastrada" tone="cyan" /></div>
    <div className="mt-4 flex gap-3 rounded-2xl p-4 text-sm leading-6" style={{ background: color + '12', color }}><Info size={20} className="shrink-0" /><p>{data.purchaseCount ? 'Somando as compras em ' + title + ' e todos os seus subníveis.' : 'Ainda não há compras em ' + title + ' neste mês. Você pode continuar navegando pelo plano.'}</p></div>

    <section className="mt-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold">{title} — últimos 6 meses</h2><span className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-[13px]">Desembolso</span></div><div className="mt-5 flex h-40 items-end justify-between gap-2">{data.history.map((item) => <div key={String(item.year) + '-' + String(item.month)} className="flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-1"><span className="max-w-full truncate text-[12px] text-slate-500">{item.totalSpent ? brl(item.totalSpent, 0) : ''}</span><span className="w-full max-w-8 rounded-t transition-all" style={{ height: String(Math.max(item.totalSpent ? 8 : 2, item.totalSpent / max * 116)) + 'px', background: item.month === data.month && item.year === data.year ? color : color + '75' }} /><small className="text-[13px] text-slate-600">{item.label}</small></div>)}</div><div className="mt-4 flex flex-wrap gap-4 text-[13px] text-slate-600"><span><i className="mr-1 inline-block h-2.5 w-2.5 rounded-sm" style={{ background: color }} />Desembolso</span><span><i className="mr-1 inline-block h-0.5 w-3 bg-cyan-500" />Consumo estimado</span></div></section>

    {composition.length > 0 ? <section className="mt-4"><h2 className="mb-2 text-[11px] font-bold">Composição de {title}</h2><div className="mb-2 flex h-1.5 overflow-hidden rounded-full bg-slate-100">{composition.map((category) => <span key={category.id} className="h-full" style={{ width: String(data.totalSpent ? category.totalSpent / data.totalSpent * 100 : 100 / composition.length) + '%', background: category.color }} />)}</div><div className="grid gap-2">{composition.map((category) => <button key={category.id} onClick={() => selectCategory(category.id)} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 text-left shadow-sm"><span className="grid h-9 w-9 place-items-center rounded-xl" style={{ background: category.color + '15' }}>{category.icon}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[10px]">{category.name}</strong><small className="block truncate text-[8px] text-slate-400">{data.totalSpent ? String(Math.round(category.totalSpent / data.totalSpent * 100)) + '% · ' : ''}{category.productCount} {category.productCount === 1 ? 'produto' : 'produtos'}</small></span><b className="text-[10px]">{brl(category.totalSpent)}</b><ChevronRight size={14} className="text-slate-300" /></button>)}</div></section> :
      <section className="mt-4"><h2 className="mb-2 text-[11px] font-bold">Produtos em {title}</h2>{products.length ? <div className="grid gap-2">{products.map((product) => <article key={product.id} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-xl" style={{ background: color + '15', color }}><Package size={16} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-[10px]">{product.name}</strong><small className="text-[8px] text-slate-400">{brl(product.averageUnitPrice)}/{product.unit} · {product.purchaseCount} {product.purchaseCount === 1 ? 'compra' : 'compras'}</small></span><b className="text-[10px]">{brl(product.amount)}</b></article>)}</div> : <p className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-[10px] text-slate-400">Nenhum produto classificado neste nível.</p>}</section>}

    {composition.length > 0 && products.length > 0 && <section className="mt-4"><h2 className="mb-2 text-[11px] font-bold">Produtos diretamente em {title}</h2><div className="grid gap-2">{products.map((product) => <article key={product.id} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-xl" style={{ background: color + '15', color }}><Package size={16} /></span><span className="min-w-0 flex-1"><strong className="block truncate text-[10px]">{product.name}</strong><small className="text-[8px] text-slate-400">{brl(product.averageUnitPrice)}/{product.unit}</small></span><b className="text-[10px]">{brl(product.amount)}</b></article>)}</div></section>}
    {data.insights.length > 0 && <section className="mt-4"><h2 className="mb-2 text-[11px] font-bold">O que explica a mudança</h2><div className="grid gap-2">{data.insights.slice(0, 4).map((insight) => <article key={insight.id} className="rounded-xl border border-slate-200 bg-white p-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg" style={{ background: color + '12', color }}>↗</span><div className="flex-1"><strong className="text-[10px]">{insight.title}</strong><p className="text-[8px] text-slate-400">{insight.description}</p></div><b className="text-xs">+{brl(insight.amount, 0)}</b></div></article>)}</div></section>}
    {loading && <div className="absolute inset-0 z-40 grid place-content-center bg-slate-50/70 backdrop-blur-[1px]"><span className="h-8 w-8 animate-spin rounded-full border-3 border-indigo-100 border-t-indigo-600" /></div>}
  </div>
}
