'use client'

import { Bell, Camera, ChevronRight, PackageOpen, Sparkles, TrendingDown, TrendingUp } from 'lucide-react'
import { brl } from '@/lib/client-api'
import type { AppScreen, DashboardDto, UserDto } from '@/lib/client-types'
import { EmptyState, MetricCard, PrimaryButton } from './ui'

export function HomeScreen({ user, data, reviewCount, navigate }: { user: UserDto; data: DashboardDto; reviewCount: number; navigate: (screen: AppScreen) => void }) {
  const positive = data.difference >= 0
  const consumptionPercent = data.totalSpent ? Math.round((data.estimatedConsumption / data.totalSpent) * 100) : 0
  return <div className="px-4 pb-6 pt-3">
    <header className="mb-3 flex items-center justify-between"><div><p className="text-[10px] text-slate-500">Olá, {user.name.split(' ')[0]}</p><h1 className="text-lg font-black tracking-tight text-slate-950">Como foi {data.monthLabel}?</h1></div><div className="flex items-center gap-2"><button aria-label="Revisões pendentes" onClick={() => navigate('reviews')} className="relative grid h-9 w-9 place-items-center rounded-full bg-white text-slate-500 shadow-sm"><Bell size={18} />{reviewCount > 0 && <span className="absolute -right-0.5 -top-0.5 grid h-4 min-w-4 place-items-center rounded-full border-2 border-white bg-rose-500 px-0.5 text-[7px] font-bold text-white">{reviewCount}</span>}</button><button aria-label="Abrir perfil" title="Perfil e configurações" onClick={() => navigate('profile')} className="grid h-9 w-9 place-items-center rounded-full bg-indigo-600 text-xs font-black text-white">{user.name.charAt(0).toUpperCase()}</button></div></header>

    {data.purchaseCount === 0 ? <>
      <section className="overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_100%_0,rgba(255,255,255,.23),transparent_26%),linear-gradient(145deg,#3730A3,#5B50E6)] p-5 text-white shadow-[0_8px_22px_rgba(67,56,202,.22)]"><span className="text-[9px] text-white/65">{data.monthLabel} · seu fluxo começa aqui</span><h2 className="mt-2 text-xl font-black leading-6">Registre sua primeira compra real.</h2><p className="mt-2 max-w-xs text-[11px] leading-5 text-white/75">O app vai separar consumo, estoque, preço e quantidade sem inventar nenhum dado.</p><button onClick={() => navigate('add')} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-bold text-indigo-700"><Camera size={16} /> Adicionar nota</button></section>
      <div className="mt-3 grid grid-cols-3 gap-2"><MetricCard label="Desembolso" value={brl(0, 0)} detail="nenhuma compra" /><MetricCard label="Consumo estimado" value={brl(0, 0)} detail="aguardando dados" tone="green" /><MetricCard label="Em estoque" value={brl(0, 0)} detail="aguardando dados" tone="cyan" /></div>
      <EmptyState icon={<PackageOpen />} title="Seu histórico está vazio" description="Cadastre uma compra manualmente ou cole o texto de uma nota para começar." action={<button onClick={() => navigate('manual')} className="text-xs font-bold text-indigo-600">Cadastrar manualmente</button>} />
    </> : <>
      <button onClick={() => navigate('flow')} className="relative w-full overflow-hidden rounded-2xl bg-[radial-gradient(circle_at_100%_0,rgba(255,255,255,.23),transparent_26%),linear-gradient(145deg,#3730A3,#5B50E6)] p-5 text-left text-white shadow-[0_8px_22px_rgba(67,56,202,.22)]"><span className="text-[9px] text-white/65">{data.monthLabel} {data.year} · análise do mês</span><h2 className="mt-2 max-w-[280px] text-lg font-black leading-5">{data.monthLabel} foi {brl(Math.abs(data.difference), 0)} {positive ? 'mais caro' : 'mais barato'} que {data.previousMonthLabel.toLowerCase()}.</h2><p className="mt-2 text-[10px] leading-4 text-white/75">{data.stockAmount > 0 ? `Mas ${brl(data.stockAmount, 0)} parecem ser estoque — não é só consumo do mês.` : 'O valor registrado parece pertencer ao consumo deste mês.'}</p><div className="mt-3 flex flex-wrap gap-1.5">{data.insights.slice(0, 4).map((insight) => <span key={insight.id} className="rounded-full bg-white/15 px-2 py-1 text-[8px] font-bold">+{brl(insight.amount, 0)}</span>)}</div><span className="mt-3 flex items-center justify-end gap-1 text-[8px] text-white/70">Por que ficou assim? <ChevronRight size={13} /></span></button>
      <div className="mt-3 grid grid-cols-3 gap-2"><MetricCard label="Desembolso" value={brl(data.totalSpent, 0)} detail="saiu da carteira" /><MetricCard label="Consumo estimado" value={brl(data.estimatedConsumption, 0)} detail={`${consumptionPercent}% do total`} tone="green" /><MetricCard label="Em estoque" value={brl(data.stockAmount, 0)} detail="para os próximos meses" tone="cyan" /></div>
      <section className="mt-3 rounded-xl border border-slate-200 bg-white p-3"><div className="flex justify-between text-[9px]"><span className="text-slate-500">Consumo real estimado do mês</span><strong className="text-emerald-600">{consumptionPercent}%</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-[linear-gradient(90deg,#635BFF,#21CDA3)]" style={{ width: `${consumptionPercent}%` }} /></div><p className="mt-1.5 text-[8px] text-slate-400">{brl(data.stockAmount, 0)} provavelmente não representam só o consumo deste mês.</p></section>
      <section className="mt-5"><div className="mb-2 flex items-center justify-between"><h2 className="text-xs font-bold">Por que ficou mais caro?</h2><button onClick={() => navigate('flow')} className="text-[9px] font-semibold text-indigo-600">Ver detalhes</button></div><div className="grid gap-2">{data.insights.slice(0, 3).map((insight) => <button key={insight.id} onClick={() => navigate('flow')} className="grid grid-cols-[34px_1fr_auto] items-center gap-2 rounded-xl border border-slate-200 bg-white p-2.5 text-left"><span className={`grid h-8 w-8 place-items-center rounded-lg ${insight.type === 'estoque' ? 'bg-emerald-50 text-emerald-600' : insight.type === 'quantidade' ? 'bg-cyan-50 text-cyan-600' : 'bg-rose-50 text-rose-500'}`}>{insight.type === 'estoque' ? '▣' : insight.type === 'quantidade' ? '▥' : 'ϟ'}</span><span className="min-w-0"><strong className="block truncate text-[10px]">{insight.title}</strong><small className="block truncate text-[8px] text-slate-400">{insight.description}</small></span><b className="text-[11px] text-emerald-600">+{brl(insight.amount, 0)}</b></button>)}</div></section>
      {data.outOfPattern.length > 0 && <section className="mt-5"><h2 className="mb-2 text-xs font-bold">Fora do seu padrão</h2><div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">{data.outOfPattern.map((item) => <article key={item.name} className="min-w-36 rounded-xl border border-slate-200 bg-white p-3"><strong className="line-clamp-2 text-[10px]">{item.name}</strong><small className="mt-1 block text-[8px] text-slate-400">Essa compra saiu do seu padrão.</small><b className="mt-2 block text-[10px]">{brl(item.amount)}</b></article>)}</div></section>}
      <PrimaryButton className="mt-5" onClick={() => navigate('add')}><Camera size={18} /> Adicionar nota <Sparkles size={15} /></PrimaryButton>
      <p className={`mt-3 flex items-center justify-center gap-1 text-[8px] ${positive ? 'text-rose-400' : 'text-emerald-500'}`}>{positive ? <TrendingUp size={13} /> : <TrendingDown size={13} />} Calculado somente com suas compras.</p>
    </>}
  </div>
}
