'use client'

import { Bell, Camera, ChevronRight, PackageOpen, Sparkles, TrendingDown, TrendingUp } from 'lucide-react'
import { brl } from '@/lib/client-api'
import type { AppScreen, DashboardDto, UserDto } from '@/lib/client-types'
import { EmptyState, MetricCard, PrimaryButton } from './ui'

export function HomeScreen({ user, data, reviewCount, navigate }: { user: UserDto; data: DashboardDto; reviewCount: number; navigate: (screen: AppScreen) => void }) {
  const positive = data.difference >= 0
  const consumptionPercent = data.totalSpent ? Math.round((data.estimatedConsumption / data.totalSpent) * 100) : 0
  const metricGrid = 'mt-4 grid grid-cols-2 gap-3 min-[420px]:grid-cols-3 [&>*:last-child]:col-span-2 min-[420px]:[&>*:last-child]:col-span-1'

  return <div className="px-4 pb-8 pt-5 min-[390px]:px-5 md:px-8 md:pt-7">
    <header className="mb-5 flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-base text-slate-600">Olá, {user.name.split(' ')[0]}</p><h1 className="mt-0.5 text-2xl font-black tracking-tight text-slate-950">Como foi {data.monthLabel}?</h1></div><div className="flex shrink-0 items-center gap-2"><button aria-label="Revisões pendentes" onClick={() => navigate('reviews')} className="relative grid h-11 w-11 place-items-center rounded-full bg-white text-slate-600 shadow-sm transition active:scale-95"><Bell size={21} />{reviewCount > 0 && <span className="absolute -right-0.5 -top-0.5 grid h-5 min-w-5 place-items-center rounded-full border-2 border-white bg-rose-500 px-1 text-[11px] font-bold text-white">{reviewCount}</span>}</button><button aria-label="Abrir perfil" title="Perfil e configurações" onClick={() => navigate('profile')} className="grid h-11 w-11 place-items-center rounded-full bg-indigo-600 text-base font-black text-white transition active:scale-95">{user.name.charAt(0).toUpperCase()}</button></div></header>

    {data.purchaseCount === 0 ? <>
      <section className="overflow-hidden rounded-3xl bg-[radial-gradient(circle_at_100%_0,rgba(255,255,255,.23),transparent_26%),linear-gradient(145deg,#3730A3,#5B50E6)] p-6 text-white shadow-[0_10px_28px_rgba(67,56,202,.22)]"><span className="text-sm text-white/75">{data.monthLabel} · seu fluxo começa aqui</span><h2 className="mt-3 text-2xl font-black leading-tight">Registre sua primeira compra real.</h2><p className="mt-3 max-w-md text-base leading-7 text-white/85">O app vai separar consumo, estoque, preço e quantidade sem inventar nenhum dado.</p><button onClick={() => navigate('add')} className="mt-6 inline-flex min-h-[52px] items-center gap-2 rounded-2xl bg-white px-5 text-base font-bold text-indigo-700 transition active:scale-[.98]"><Camera size={20} /> Adicionar nota</button></section>
      <div className={metricGrid}><MetricCard label="Desembolso" value={brl(0, 0)} detail="nenhuma compra" /><MetricCard label="Consumo estimado" value={brl(0, 0)} detail="aguardando dados" tone="green" /><MetricCard label="Em estoque" value={brl(0, 0)} detail="aguardando dados" tone="cyan" /></div>
      <EmptyState icon={<PackageOpen size={26} />} title="Seu histórico está vazio" description="Cadastre uma compra manualmente ou cole o texto de uma nota para começar." action={<button onClick={() => navigate('manual')} className="min-h-11 rounded-xl px-4 text-sm font-bold text-indigo-600">Cadastrar manualmente</button>} />
    </> : <>
      <button onClick={() => navigate('flow')} className="relative w-full overflow-hidden rounded-3xl bg-[radial-gradient(circle_at_100%_0,rgba(255,255,255,.23),transparent_26%),linear-gradient(145deg,#3730A3,#5B50E6)] p-6 text-left text-white shadow-[0_10px_28px_rgba(67,56,202,.22)] transition active:scale-[.99]"><span className="text-sm text-white/75">{data.monthLabel} {data.year} · análise do mês</span><h2 className="mt-3 max-w-xl text-2xl font-black leading-tight">{data.monthLabel} foi {brl(Math.abs(data.difference), 0)} {positive ? 'mais caro' : 'mais barato'} que {data.previousMonthLabel.toLowerCase()}.</h2><p className="mt-3 text-base leading-7 text-white/85">{data.stockAmount > 0 ? `Mas ${brl(data.stockAmount, 0)} parecem ser estoque — não é só consumo do mês.` : 'O valor registrado parece pertencer ao consumo deste mês.'}</p><div className="mt-4 flex flex-wrap gap-2">{data.insights.slice(0, 4).map((insight) => <span key={insight.id} className="rounded-full bg-white/15 px-3 py-1.5 text-sm font-bold">+{brl(insight.amount, 0)}</span>)}</div><span className="mt-4 flex items-center justify-end gap-1 text-sm text-white/80">Por que ficou assim? <ChevronRight size={18} /></span></button>

      <div className={metricGrid}><MetricCard label="Desembolso" value={brl(data.totalSpent, 0)} detail="saiu da carteira" /><MetricCard label="Consumo estimado" value={brl(data.estimatedConsumption, 0)} detail={`${consumptionPercent}% do total`} tone="green" /><MetricCard label="Em estoque" value={brl(data.stockAmount, 0)} detail="para os próximos meses" tone="cyan" /></div>

      <section className="mt-4 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium text-slate-700">Consumo real estimado do mês</span><strong className="text-base text-emerald-600">{consumptionPercent}%</strong></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-[linear-gradient(90deg,#635BFF,#21CDA3)] transition-[width] duration-500" style={{ width: `${consumptionPercent}%` }} /></div><p className="mt-2 text-sm leading-5 text-slate-600">{brl(data.stockAmount, 0)} provavelmente não representam só o consumo deste mês.</p></section>

      <section className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-xl font-bold tracking-tight text-slate-950">Por que ficou mais caro?</h2><button onClick={() => navigate('flow')} className="min-h-11 rounded-xl px-3 text-sm font-semibold text-indigo-600">Ver detalhes</button></div><div className="grid gap-3">{data.insights.slice(0, 3).map((insight) => <button key={insight.id} onClick={() => navigate('flow')} className="grid min-h-20 grid-cols-[44px_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition active:scale-[.99]"><span className={`grid h-11 w-11 place-items-center rounded-xl text-base ${insight.type === 'estoque' ? 'bg-emerald-50 text-emerald-600' : insight.type === 'quantidade' ? 'bg-cyan-50 text-cyan-600' : 'bg-rose-50 text-rose-500'}`}>{insight.type === 'estoque' ? '▣' : insight.type === 'quantidade' ? '▥' : 'ϟ'}</span><span className="min-w-0"><strong className="block text-base leading-5 text-slate-900">{insight.title}</strong><small className="mt-1 block text-sm leading-5 text-slate-600">{insight.description}</small></span><b className="whitespace-nowrap text-sm text-emerald-600">+{brl(insight.amount, 0)}</b></button>)}</div></section>

      {data.outOfPattern.length > 0 && <section className="mt-7"><h2 className="mb-3 text-xl font-bold tracking-tight text-slate-950">Fora do seu padrão</h2><div className="-mx-4 flex snap-x gap-3 overflow-x-auto px-4 pb-2 scrollbar-none min-[390px]:-mx-5 min-[390px]:px-5 md:-mx-8 md:px-8">{data.outOfPattern.map((item) => <article key={item.name} className="min-w-56 snap-start rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><strong className="line-clamp-2 text-base leading-5 text-slate-900">{item.name}</strong><small className="mt-2 block text-sm leading-5 text-slate-600">Essa compra saiu do seu padrão.</small><b className="mt-3 block text-base">{brl(item.amount)}</b></article>)}</div></section>}

      <PrimaryButton className="mt-7" onClick={() => navigate('add')}><Camera size={21} /> Adicionar nota <Sparkles size={17} /></PrimaryButton>
      <p className={`mt-4 flex items-center justify-center gap-1.5 text-sm ${positive ? 'text-rose-500' : 'text-emerald-600'}`}>{positive ? <TrendingUp size={16} /> : <TrendingDown size={16} />} Calculado somente com suas compras.</p>
    </>}
  </div>
}
